export const actionTypes = {
  uiDisplayAlert: "[ui] Display Alert",
  uiClearAlert: "[ui] Clear Alert",
  eventSelected: "[event] Select Event",
  eventStartAdd: "[event] Add New Event Request Started",
  eventAddNew: "[event] Add new Event",
  eventAddSelectedSlot: "[event] Add Selected Slot Event",
  eventClearActive: "[event] Clear Active Event",
  eventUpdated: "[event] Event Updated",
  eventDeleted: "[event] Event Deleted",
  eventLoaded: "[event] Event Loaded from API",
  authCheckingLoginState: "[auth] Checking Login State",
  authLoginStateChecked: "[auth] Checking Login State Finished",
  authStartLogin: "[auth] Start Login",
  authLogin: "[auth] Login",
  authStartRegister: "[auth] Start Register",
  authRegister: "[auth] Register",
  authStartRefreshToken: "[auth] Start Refresh token",
  authRefreshToken: "[auth] Start token",
  authLogout: "[auth] Logout",
};
